//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tBOT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class API
    {
        public int Id { get; set; }
        public string APP { get; set; }
        public string Connector { get; set; }
        public string EndPoint { get; set; }
        public string Version { get; set; }
        public string SchemaUrl { get; set; }
    }
}
