//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tBOT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Api_Config
    {
        public int Id { get; set; }
        public int Api_Id { get; set; }
        public int Env_Id { get; set; }
        public int Auth_Id { get; set; }
    }
}
