//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tBOT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndPointObjectGroup
    {
        public int Id { get; set; }
        public int EndPointObjectId { get; set; }
        public string Section { get; set; }
    
        public virtual EndPointObject EndPointObject { get; set; }
    }
}
