//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tBOT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Validation
    {
        public int Id { get; set; }
        public Nullable<int> Api_Config_Id { get; set; }
        public string Type { get; set; }
        public string Expected_Value { get; set; }
    }
}
