//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tBOT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_EndPointObjectComponent_By_EndPointObjectGroupIdWise
    {
        public int EndPointObjectGroupId { get; set; }
        public string EndPointObjectGroupSection { get; set; }
        public Nullable<int> InstanceId { get; set; }
        public Nullable<int> EndPointObjectId { get; set; }
        public Nullable<int> EndPointId { get; set; }
        public string Instance { get; set; }
        public string EndPoint { get; set; }
        public Nullable<int> EndPointObjectComponentId { get; set; }
        public string EndPointObjectComponentName { get; set; }
        public string EndPointObjectComponentValue { get; set; }
    }
}
