//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tBOT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_EndPointObject_By_Count
    {
        public int InstanceId { get; set; }
        public int EndPointId { get; set; }
        public string Instance { get; set; }
        public string EndPoint { get; set; }
        public Nullable<int> Object { get; set; }
    }
}
